version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:latest"
    volumes:
      - ${HA_CONFIG_PATH}:/config
      - /etc/localtime:/etc/localtime:ro
      - ./homeassistant/hacs/init_script.sh:/config/init_script.sh
      
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - PYTHONUNBUFFERED=1
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    restart: unless-stopped
    privileged: true
    network_mode: host
    command: /bin/bash -c "chmod +x /config/init_script.sh; /config/init_script.sh; python -m homeassistant --config /config"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.28.4
    restart: unless-stopped
    volumes:
      - ${ZIGBEE2MQTT_DATA}:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - "8080:8080"
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - ZIGBEE_ADAPTER_TTY=${ZIGBEE_ADAPTER_TTY:-/dev/ttyACM0}
    devices:
      - ${ZIGBEE_ADAPTER_TTY:-/dev/ttyACM0}:${ZIGBEE_ADAPTER_TTY:-/dev/ttyACM0}
    depends_on:
      - mqtt

  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome:latest
    volumes:
      - ${ESPHOME_CONFIG}:/config
    restart: unless-stopped
    privileged: true
    network_mode: host

  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ${MQTT_CONFIG_PATH}:/mqtt/config
      - ${MQTT_LOG_PATH}:/mqtt/log
      - ${MQTT_DATA_PATH}:/mqtt/data
    restart: unless-stopped