version: '3.8'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:latest"
    volumes:
      - ${HA_CONFIG_PATH:-./volumes/homeassistant}:/config
      - /etc/localtime:/etc/localtime:ro
      - ./homeassistant/hacs/init_script.sh:/config/init_script.sh
    environment:
      - TZ=${TZ:-America/Argentina/Buenos_Aires}
      - PYTHONUNBUFFERED=1
    secrets:
      - mqtt_username
      - mqtt_password
      - ha_github_token
    restart: unless-stopped
    privileged: true
    networks:
      - domotic
    command: /bin/bash -c "chmod +x /config/init_script.sh; /config/init_script.sh; python -m homeassistant --config /config"
    depends_on:
      - mqtt

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.28.4
    restart: unless-stopped
    volumes:
      - ${ZIGBEE2MQTT_DATA:-./volumes/zigbee2mqtt}:/app/data
      - /run/udev:/run/udev:ro
      - ./zigbee2mqtt/scripts/init_mqtt.sh:/init_mqtt.sh
      - ./zigbee2mqtt/config:/app/config
    ports:
      - "8080:8080"
    environment:
      - TZ=${TZ:-America/Argentina/Buenos_Aires}
      - ZIGBEE_ADAPTER_TTY=${ZIGBEE_ADAPTER_TTY:-/dev/ttyACM0}
      - MQTT_SERVER=mqtt://mqtt:1883
    secrets:
      - mqtt_username
      - mqtt_password
    devices:
      - ${ZIGBEE_ADAPTER_TTY:-/dev/ttyACM0}:${ZIGBEE_ADAPTER_TTY:-/dev/ttyACM0}
    command: ["/bin/sh", "/init_mqtt.sh"]
    networks:
      - domotic
    depends_on:
      - mqtt

  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome:latest
    volumes:
      - ${ESPHOME_CONFIG:-./volumes/esphome}:/config
    restart: unless-stopped
    privileged: true
    networks:
      - domotic

  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./volumes/mosquitto/config:/mqtt/config
      - ./volumes/mosquitto/log:/mqtt/log
      - ./volumes/mosquitto/data:/mqtt/data
      - ./mosquitto/scripts/init_mqtt.sh:/init.sh
    secrets:
      - mqtt_username
      - mqtt_password
    restart: unless-stopped
    networks:
      - domotic
    command: /bin/sh -c "chmod +x /init.sh && /init.sh && mosquitto -c /mqtt/config/mosquitto.conf"
    user: root

networks:
  domotic:
    name: domotic
    driver: bridge

secrets:
  mqtt_username:
    file: ./secrets/mqtt_username.txt
  mqtt_password:
    file: ./secrets/mqtt_password.txt
  ha_github_token:
    file: ./secrets/ha_github_token.txt