version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:latest"
    volumes:
      - ${HA_CONFIG_PATH}:/config
      - /etc/localtime:/etc/localtime:ro
      - ./homeassistant/hacs/init_script.sh:/config/init_script.sh
      
    environment:
      - TZ=America/Argentina/Buenos_Aires
    restart: unless-stopped
    privileged: true
    network_mode: host
    command: /bin/bash -c "chmod +x /config/init_script.sh; /config/init_script.sh; python -m homeassistant --config /config"

  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.15
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ${MQTT_CONFIG_PATH}:/mqtt/config
      - ${MQTT_LOG_PATH}:/mqtt/log
      - ${MQTT_DATA_PATH}:/mqtt/data
    restart: unless-stopped