version: '3.8'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:latest"
    volumes:
      - ${HA_CONFIG_PATH:-./volumes/homeassistant}:/config
      - /etc/localtime:/etc/localtime:ro
      - ./homeassistant/hacs/init_script.sh:/config/init_script.sh
      - /dev:/dev  # Importante: Dar acceso a dispositivos USB para ZHA
    ports:
      - "8123:8123"
    environment:
      - TZ=${TZ:-America/Argentina/Buenos_Aires}
      - PYTHONUNBUFFERED=1
    secrets:
      - mqtt_username
      - mqtt_password
      - ha_github_token
    restart: unless-stopped
    privileged: true  # Necesario para acceder al adaptador Zigbee
    networks:
      - domotic
    command: /bin/bash -c "chmod +x /config/init_script.sh; /config/init_script.sh; python -m homeassistant --config /config"
    depends_on:
      mqtt:
        condition: service_healthy

  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome:latest
    volumes:
      - ${ESPHOME_CONFIG:-./volumes/esphome}:/config
    ports:
      - "6052:6052"
    restart: unless-stopped
    privileged: true
    networks:
      - domotic

  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./volumes/mosquitto/config:/mqtt/config
      - ./volumes/mosquitto/log:/mqtt/log
      - ./volumes/mosquitto/data:/mqtt/data
      - ./mosquitto/scripts/init_mqtt.sh:/init.sh
    secrets:
      - mqtt_username
      - mqtt_password
    restart: unless-stopped
    networks:
      - domotic
    user: root
    command: /bin/sh -c "chmod +x /init.sh && /init.sh && mosquitto -c /mqtt/config/mosquitto.conf"
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 mosquitto_pub -h localhost -p 1883 -t test -m test || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  ring-mqtt:
    container_name: ring-mqtt
    image: tsightler/ring-mqtt:latest
    volumes:
      - ./volumes/ring-mqtt/config:/config
    environment:
      - TZ=${TZ:-America/Argentina/Buenos_Aires}
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - MQTT_USERNAME=${MQTT_USERNAME:-}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-}
      - RING_TOKEN=${RING_TOKEN:-}
      - RING_LOCATION_ID=${RING_LOCATION_ID:-}
      - RING_DEVICE_ID=${RING_DEVICE_ID:-}
      - RING_REFRESH_TOKEN=${RING_REFRESH_TOKEN:-}
    restart: unless-stopped
    networks:
      - domotic
    depends_on:
      mqtt:
        condition: service_healthy

networks:
  domotic:
    name: domotic
    driver: bridge

secrets:
  mqtt_username:
    file: ./secrets/mqtt_username.txt
  mqtt_password:
    file: ./secrets/mqtt_password.txt
  ha_github_token:
    file: ./secrets/ha_github_token.txt