version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ${HA_CONFIG_PATH}:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Argentina/Buenos_Aires
    restart: unless-stopped
    privileged: true
    network_mode: host

  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=America/Argentina/Buenos_Aires
    ports:
      - "1880:1880"
    volumes:
      - ${NR_DATA_PATH}:/data

  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.15
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ${MQTT_CONFIG_PATH}:/mqtt/config
      - ${MQTT_LOG_PATH}:/mqtt/log
      - ${MQTT_DATA_PATH}:/mqtt/data
    restart: unless-stopped