homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt:1883
  user: "${MQTT_USERNAME}"
  password: "${MQTT_PASSWORD}"
serial:
  port: "${ZIGBEE_ADAPTER_TTY:-/dev/ttyACM0}"
  adapter: ezsp
frontend:
  port: 8080
advanced:
  log_level: debug
  network_key: GENERATE
  adapter_concurrent: 1
  adapter_delay: 100
device_options:
  legacy: true
devices: 
  # Los dispositivos apareados aparecerán aquí automáticamente 