homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mqtt:1883
  user: "${MQTT_USERNAME}"
  password: "${MQTT_PASSWORD}"
serial:
  port: "${ZIGBEE_ADAPTER_TTY:-/dev/ttyUSB0}"
  adapter: ezsp
frontend:
  port: 8080
advanced:
  log_level: info
  network_key: GENERATE
devices: 
  # Los dispositivos apareados aparecerán aquí automáticamente 