# Ejemplos de automatizaciones para Home Assistant
# IMPORTANTE: Este archivo solo contiene ejemplos con fines educativos.
# Se recomienda crear tus propias automatizaciones específicas en la interfaz web
# o mantener archivos de configuración privados.
#
# Para más información: https://www.home-assistant.io/docs/automation/

# Ejemplo 1: Notificación simple al iniciar Home Assistant
- id: 'ejemplo_notificacion_inicio'
  alias: 'Ejemplo: Notificación de inicio'
  description: 'Ejemplo educativo - Envía una notificación cuando inicia el sistema'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: persistent_notification.create
      data:
        title: "Ejemplo"
        message: "Esta es una notificación de ejemplo"

# Ejemplo 2: Automatización basada en tiempo
- id: 'ejemplo_tiempo'
  alias: 'Ejemplo: Acción programada'
  description: 'Ejemplo educativo - Ejecuta una acción en un momento específico'
  trigger:
    - platform: time
      at: '07:30:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: persistent_notification.create
      data:
        title: "Buenos días"
        message: "Este es un ejemplo de acción programada"

# ════════════════════════════════════════════════════════════
# PARA PERSONALIZAR:
# 1. Crea tus automatizaciones desde la interfaz web de Home Assistant
# 2. Usa la integración con Google Assistant, Alexa u otros servicios
# 3. Configura las automatizaciones según las necesidades específicas de tu hogar
# ════════════════════════════════════════════════════════════ 